create table if not exists recepciones (
  id serial primary key,
  numero_formulario text,
  fecha_ingreso date,
  cliente text,
  direccion text,
  cuit text,
  telefono text,
  email text,
  adjunta_factura boolean default false,
  fecha_factura date,
  numero_factura text,
  garantia text default 'NO',
  periodo_garantia text default 'NO',
  diagnostico_costo text,
  condiciones_diagnostico text,
  observaciones text,
  segmento text,
  equipo text,
  modelo_codigo text,
  numero_serie text,
  accesorios text,
  falla_denunciada text,
  estado_general text,
  estado_taller text default 'INGRESO',
  tareas jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);
